### ISSUE TITLE
The app crashed after I clicked on the play button.

### ISSUE THREAD

**Issue by sagorahmed** [BlunT76/cardash#2]
#### Expected behavior
The users should be able to click on the play button and play the songs without getting any trouble.

#### Actual behavior
When I clicked on the play button, then the app crashed. 

#### How to reproduce
Here is every possible detail to reproduce the bug.
1. Open the app.
2. Click on the "play" button. (Make sure, the status of max is like this "MAX: OFF".)
3. Notice the error.

* App version: 0.1.8
* Operating system: Android 6.0.1

#### Recording Of The Bug
![buug](https://media.giphy.com/media/XD3d7T08eus2trlouR/giphy.gif)

#### LogCat
```
5-26 14:14:58.356   639   675 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

05-26 14:14:58.356   639   675 E AndroidRuntime: Process: com.minimalcardashboard, PID: 639

05-26 14:14:58.356   639   675 E AndroidRuntime: com.facebook.react.common.c: undefined is not an object (evaluating 'l[c].path'), stack:

05-26 14:14:58.356   639   675 E AndroidRuntime: value@396:1973

05-26 14:14:58.356   639   675 E AndroidRuntime: handlePlayPause@396:1138

05-26 14:14:58.356   639   675 E AndroidRuntime: onPress@396:2466

05-26 14:14:58.356   639   675 E AndroidRuntime: touchableHandlePress@327:1912

05-26 14:14:58.356   639   675 E AndroidRuntime: touchableHandlePress@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: _performSideEffectsForTransition@195:9071

05-26 14:14:58.356   639   675 E AndroidRuntime: _performSideEffectsForTransition@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: _receiveSignal@195:7784

05-26 14:14:58.356   639   675 E AndroidRuntime: _receiveSignal@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: touchableHandleResponderRelease@195:5072

05-26 14:14:58.356   639   675 E AndroidRuntime: touchableHandleResponderRelease@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: y@90:576

05-26 14:14:58.356   639   675 E AndroidRuntime: P@90:719

05-26 14:14:58.356   639   675 E AndroidRuntime: E@90:773

05-26 14:14:58.356   639   675 E AndroidRuntime: M@90:1940

05-26 14:14:58.356   639   675 E AndroidRuntime: H@90:2699

05-26 14:14:58.356   639   675 E AndroidRuntime: forEach@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: j@90:2499

05-26 14:14:58.356   639   675 E AndroidRuntime: <unknown>@90:14003

05-26 14:14:58.356   639   675 E AndroidRuntime: Ue@90:83341

05-26 14:14:58.356   639   675 E AndroidRuntime: De@90:13673

05-26 14:14:58.356   639   675 E AndroidRuntime: We@90:13846

05-26 14:14:58.356   639   675 E AndroidRuntime: receiveTouches@90:14605

05-26 14:14:58.356   639   675 E AndroidRuntime: value@28:3311

05-26 14:14:58.356   639   675 E AndroidRuntime: <unknown>@28:822

05-26 14:14:58.356   639   675 E AndroidRuntime: value@28:2565

05-26 14:14:58.356   639   675 E AndroidRuntime: value@28:794

05-26 14:14:58.356   639   675 E AndroidRuntime: value@-1

05-26 14:14:58.356   639   675 E AndroidRuntime: 

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source)

05-26 14:14:58.356   639   675 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by BlunT76** [comment]
Thanks for the report, I'll take a look

**Comment by BlunT76** [comment]
v0.1.9 does fix that issue, please try it and let me know if it works as i don't be able to reproduce the issue.

**Comment by sagorahmed** [comment]
Hi @BlunT76 
This is not occurring anymore on the v0.1.9. Thanks for fixing the issue.

**Comment by BlunT76** [comment]
Good, thanks :)
